### ISSUE TITLE
Prepare module documentation

### ISSUE THREAD

**Issue by calin-marian** [dreamproduction/places_api_autocomplete#11]

**Comment by iulia-na** [comment]
**Google Places API Autocomplete widget** module adds suggestions from google places API to a text field, similar to Google Maps. 

# How to configure the module
1. Go to admin/config/services/places
2. Insert the Google API Key

# How to get a Google API key

1. Go to https://code.google.com/apis/console/ 
2. Create a new project
3. Enable Google Places API
4. Go to Credentials
5. Create New Key 
6. Select Server key

# How to configure the parameters
Parameters such as location, country, language can be configured either per field or in the general settings of the module. Documentation about the parameters, can be found here (https://developers.google.com/places/webservice/autocomplete#place_autocomplete_requests)

Google Places API Autocomplete widget is being developed by ....

**Comment by calin-marian** [comment]
i added it to README.md, and create a README.txt based on it
