### ISSUE TITLE
Add options default value when module install

### ISSUE THREAD

**Issue by radubutco** [dreamproduction/places_api_autocomplete#22]

**Comment by calin-marian** [comment]
for this issue we discussed creating a function for defining default options, something along this lines:

    function places_api_autocomplete_get_default_options() {
      return array(
        'option1' => 'default_value1',
        'option2' => 'default_value2',
        .............................................
      );
    }

and then, where the options are needed:

    $options = variable_get('places_api_autocomplete_options', places_api_autocomplete_get_default_options());

Also, please use a shorter name for the php variable for the options, instead of $places_api_autocomplete_options you could use $options
