### ISSUE TITLE
Make sure it meets drupal coding standards (Coder module)

### ISSUE THREAD

**Issue by calin-marian** [dreamproduction/places_api_autocomplete#4]
https://www.drupal.org/coding-standards
http://drupal.org/project/coder

**Comment by rbmboogie** [comment]
I have ran Code sniffer on the places_api_autocomplete.module.
Bellow you can see the output.
--------------------------------------------------------------------------------
FOUND 11 ERROR(S) AFFECTING 9 LINE(S)
--------------------------------------------------------------------------------
   2 | ERROR | Missing file doc comment
  35 | ERROR | Missing function doc comment
  39 | ERROR | Variable "cacheObject" is camel caps format. do not use mixed
     |       | case (camelCase), use lower case and _
  40 | ERROR | Expected "if (...) {\n"; found "if (...){\n"
  42 | ERROR | Expected "else {\n"; found "else{\n"
  42 | ERROR | else must start on a new line
  47 | ERROR | Variable "placesApi" is camel caps format. do not use mixed case
     |       | (camelCase), use lower case and _
  47 | ERROR | Variable "cacheObject" is camel caps format. do not use mixed
     |       | case (camelCase), use lower case and _
  48 | ERROR | Variable "placesApi" is camel caps format. do not use mixed case
     |       | (camelCase), use lower case and _
  70 | ERROR | Expected 1 space after "=>"; 2 found
 163 | ERROR | Files must end in a single new line character
--------------------------------------------------------------------------------

**Comment by calin-marian** [comment]
Most of them are fixed, but not all of them, will take care of them later.

**Comment by calin-marian** [comment]
done
